program: LeNet_FashionMNIST_wandb_sweep_cmd.py
method: bayes
metric:
  # goal: minimize
  # name: eval/val_loss
  goal: maximize
  name: eval/val_acc
parameters:
  lr:
    min: 0.005
    max: 0.2
  batch_size:
    distribution: q_log_uniform_values
    q: 64
    min: 128
    max: 512
  epochs:
    distribution: q_log_uniform_values
    q: 5
    min: 15
    max: 30
early_terminate:
  type: hyperband
  s: 3
  eta: 3
  max_iter: 81
command:
  - ${env}
  - python
  - ${program}
  - ${args}